#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    lock_passwd: true  # Lock password (no password auth)

ssh_pwauth: false  # Disable password authentication for SSH

runcmd:
  - mkdir -p /home/ubuntu/.ssh
  - chown ubuntu:ubuntu /home/ubuntu/.ssh
  - chmod 0700 /home/ubuntu/.ssh
  - echo '${ssh_public_key}' > /home/ubuntu/.ssh/authorized_keys  # Overwrite to ensure key is added
  - chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
  - chmod 0600 /home/ubuntu/.ssh/authorized_keys
  - sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config  # Disable password auth
  - systemctl restart sshd  # Restart SSH daemon
  - echo "Cloud-init completed. Key-only auth enabled." > /var/log/cloud-init-complete.log  # For debugging